// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneNNC3ShoPndKoeHD2pzipQ-NC3yfqmg',
    appId: '1:1013943006713:web:8a94c0f081b16387d33928',
    messagingSenderId: '1013943006713',
    projectId: 'hackbeanpot-92e48',
    authDomain: 'hackbeanpot-92e48.firebaseapp.com',
    storageBucket: 'hackbeanpot-92e48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFec3Lbn01kzZUfJ6l9fzmaG-OhniGbWs',
    appId: '1:1013943006713:android:44c7b57310b2495ad33928',
    messagingSenderId: '1013943006713',
    projectId: 'hackbeanpot-92e48',
    storageBucket: 'hackbeanpot-92e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAxIXXvqz-dZBVj4EGVqrJXpvB_WAE8oQ',
    appId: '1:1013943006713:ios:735ae74c94f305c8d33928',
    messagingSenderId: '1013943006713',
    projectId: 'hackbeanpot-92e48',
    storageBucket: 'hackbeanpot-92e48.firebasestorage.app',
    iosBundleId: 'com.example.hackbeanpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAxIXXvqz-dZBVj4EGVqrJXpvB_WAE8oQ',
    appId: '1:1013943006713:ios:735ae74c94f305c8d33928',
    messagingSenderId: '1013943006713',
    projectId: 'hackbeanpot-92e48',
    storageBucket: 'hackbeanpot-92e48.firebasestorage.app',
    iosBundleId: 'com.example.hackbeanpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBneNNC3ShoPndKoeHD2pzipQ-NC3yfqmg',
    appId: '1:1013943006713:web:45b2a2cd3f5d1253d33928',
    messagingSenderId: '1013943006713',
    projectId: 'hackbeanpot-92e48',
    authDomain: 'hackbeanpot-92e48.firebaseapp.com',
    storageBucket: 'hackbeanpot-92e48.firebasestorage.app',
  );
}
